# -*- coding: utf-8 -*-
"""Arabic_AI_Text_Detection_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ceyYUyzPpWHKvuHPjcB2Ra9qbpi_KEHb

# Phase 1: Big Data Environment Setup & Data Acquisition

Install + Imports
"""

# Install
!pip install datasets pandas

# Imports
from datasets import load_dataset
import pandas as pd
import os

"""Load Dataset"""

dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

print("Dataset loaded successfully!")
print(dataset)

"""Inspect Structure"""

# Check one sample from each split
print(dataset['by_polishing'][0])
print(dataset['from_title'][0])
print(dataset['from_title_and_content'][0])

"""Convert to ML Dataset"""

data = []

splits = ['by_polishing', 'from_title', 'from_title_and_content']

for split in splits:
    for item in dataset[split]:

        # Human text
        data.append({
            "text": item["original_abstract"],
            "label": 0
        })

        # AI texts
        data.append({"text": item["allam_generated_abstract"], "label": 1})
        data.append({"text": item["jais_generated_abstract"], "label": 1})
        data.append({"text": item["llama_generated_abstract"], "label": 1})
        data.append({"text": item["openai_generated_abstract"], "label": 1})

df = pd.DataFrame(data)

print("DataFrame created!")

"""Exploration"""

print("\nSample Data:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nLabel Distribution:")
print(df['label'].value_counts())

"""Save Dataset"""

# Create folder
os.makedirs("data", exist_ok=True)

# Save file
df.to_csv("data/data.csv", index=False)

print("Dataset saved successfully at: data/data.csv")

# Install PySpark (Colab)
!pip install pyspark

"""Spark Session"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("AI Text Detection") \
    .getOrCreate()

print("Spark Session Created")

spark_df = spark.read.csv("data/data.csv", header=True, inferSchema=True)

spark_df.show(5)

Schema + count

print("Schema:")
spark_df.printSchema()

print("Count:")
print(spark_df.count())

print("Label Distribution (Spark):")
spark_df.groupBy("label").count().show()

df.to_csv("data/data.csv", index=False, encoding="utf-8-sig")

spark_df = spark.read.option("header", True) \
    .option("multiLine", True) \
    .option("quote", '"') \
    .option("escape", '"') \
    .csv("data/data.csv")

from pyspark.sql.functions import col

spark_df = spark_df.withColumn("label", col("label").cast("int"))

"""Correct Spark label distribution"""

spark_df.groupBy("label").count().show()

spark_df.write.mode("overwrite").parquet("data/processed_data.parquet")

"""
 # Phase 2: Distributed Data Preprocessing & Storage"""

from pyspark.sql import SparkSession

# Initialize Spark
spark = SparkSession.builder.appName("Phase2").getOrCreate()

# Load CSV into Spark
spark_df = spark.read.option("header", True) \
    .option("multiLine", True) \
    .option("quote", '"') \
    .option("escape", '"') \
    .csv("data/data.csv")

spark_df.show(5)

import re

# Normalize Arabic characters
def normalize_arabic(text):
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "و", text)
    text = re.sub("ئ", "ي", text)
    text = re.sub("ة", "ه", text)
    return text

# Remove diacritics
def remove_diacritics(text):
    arabic_diacritics = re.compile("""
        ّ|َ|ً|ُ|ٌ|ِ|ٍ|ْ|ـ
    """, re.VERBOSE)
    return re.sub(arabic_diacritics, '', text)

# Basic cleaning
def clean_text(text):
    text = remove_diacritics(text)
    text = normalize_arabic(text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    return text

from pyspark.sql.functions import udf
from pyspark.sql.types import StringType

# Apply cleaning using UDF
clean_udf = udf(lambda x: clean_text(x) if x else "", StringType())

spark_df = spark_df.withColumn("clean_text", clean_udf(spark_df["text"]))

spark_df.show(5)

# Simple Arabic stopwords list
arabic_stopwords = set([
    "في", "من", "على", "و", "الى", "عن", "هذا", "هذه", "ذلك", "كما", "مع", "كان", "قد"
])

def remove_stopwords(text):
    words = text.split()
    filtered = [w for w in words if w not in arabic_stopwords]
    return " ".join(filtered)

stop_udf = udf(lambda x: remove_stopwords(x), StringType())

spark_df = spark_df.withColumn("clean_text", stop_udf(spark_df["clean_text"]))

spark_df.show(5)

# Simple stemming (first 4 chars)
def simple_stem(text):
    words = text.split()
    stemmed = [w[:4] for w in words]
    return " ".join(stemmed)

stem_udf = udf(lambda x: simple_stem(x), StringType())

spark_df = spark_df.withColumn("processed_text", stem_udf(spark_df["clean_text"]))

spark_df.select("text", "processed_text").show(5)

# Save in Parquet format
spark_df.write.mode("overwrite").parquet("data/processed_phase2.parquet")

from pyspark.sql.functions import explode, split

# Tokenize words
words_df = spark_df.select(explode(split("processed_text", " ")).alias("word"))
words_df = words_df.filter(words_df.word != "")

# Count frequency
word_counts = words_df.groupBy("word").count().orderBy("count", ascending=False)

word_counts.show(10)

# Calculate TTR
total_words = words_df.count()
unique_words = words_df.select("word").distinct().count()

ttr = unique_words / total_words

print("Total Words:", total_words)
print("Unique Words:", unique_words)
print("TTR:", ttr)

"""N-Gram analysis"""

from pyspark.ml.feature import NGram

words_split = spark_df.withColumn("words", split("processed_text", " "))

ngram = NGram(n=2, inputCol="words", outputCol="bigrams")

ngram_df = ngram.transform(words_split)

ngram_df.select("bigrams").show(5, truncate=False)

# Convert Spark DataFrame column to RDD
text_rdd = spark_df.select("processed_text").rdd.flatMap(lambda x: x)

# MapReduce word count
word_counts_mr = text_rdd.flatMap(lambda line: line.split()) \
    .map(lambda word: (word, 1)) \
    .reduceByKey(lambda a, b: a + b)

print(word_counts_mr.take(10))

"""

 # Phase 3: Scalable Feature Engineering & Distributed Modeling"""

from pyspark.sql.functions import col
from pyspark.sql.functions import udf
from pyspark.sql.types import IntegerType
import re

"""Feature 6 (Multiple Elongations)"""

# Count multiple elongations (e.g., loooong letters)

def count_multiple_elongations(text):
    return len(re.findall(r'(.)\1{2,}', text))

elong_udf = udf(lambda x: count_multiple_elongations(x), IntegerType())

spark_df = spark_df.withColumn("feat_6_elong", elong_udf(col("text")))

"""Feature 29 (Semicolons)"""

# Count semicolons

def count_semicolons(text):
    return text.count(";")

semi_udf = udf(lambda x: count_semicolons(x), IntegerType())

spark_df = spark_df.withColumn("feat_29_semicolon", semi_udf(col("text")))

"""Feature 52 (Interjections)"""

# Arabic interjections list

interjections = ["يا", "اه", "او", "آه", "واو"]

def count_interjections(text):
    words = text.split()
    return sum(1 for w in words if w in interjections)

interj_udf = udf(lambda x: count_interjections(x), IntegerType())

spark_df = spark_df.withColumn("feat_52_interj", interj_udf(col("text")))

"""Feature 75 (Active Voice Approx)"""

# Simple approximation: count verbs-like patterns

def count_active_voice(text):
    words = text.split()
    return sum(1 for w in words if w.startswith("ي") or w.startswith("ت"))

active_udf = udf(lambda x: count_active_voice(x), IntegerType())

spark_df = spark_df.withColumn("feat_75_active", active_udf(col("text")))

"""Feature 98 (BERT Simplified)"""

# Approximate BERT feature (text length proxy)

def bert_proxy(text):
    return len(text.split())

bert_udf = udf(lambda x: bert_proxy(x), IntegerType())

spark_df = spark_df.withColumn("feat_98_bert", bert_udf(col("text")))

"""Check Features"""

spark_df.select(
    "feat_6_elong",
    "feat_29_semicolon",
    "feat_52_interj",
    "feat_75_active",
    "feat_98_bert"
).show(5)

"""Tokenize + TF-IDF (Spark ML)"""

from pyspark.ml.feature import Tokenizer, StopWordsRemover, HashingTF, IDF

# Tokenize
tokenizer = Tokenizer(inputCol="processed_text", outputCol="words")

# (optional) extra stopwords remove at ML stage
remover = StopWordsRemover(inputCol="words", outputCol="filtered_words")

# TF
hashingTF = HashingTF(inputCol="filtered_words", outputCol="tf_features", numFeatures=10000)

# IDF
idf = IDF(inputCol="tf_features", outputCol="tfidf_features")

# Apply pipeline steps
df_tokens = tokenizer.transform(spark_df)
df_filtered = remover.transform(df_tokens)
df_tf = hashingTF.transform(df_filtered)
idf_model = idf.fit(df_tf)
df_tfidf = idf_model.transform(df_tf)

df_tfidf.select("tfidf_features").show(5)

"""Combine ALL features"""

from pyspark.ml.feature import VectorAssembler

assembler = VectorAssembler(
    inputCols=[
        "tfidf_features",
        "feat_6_elong",
        "feat_29_semicolon",
        "feat_52_interj",
        "feat_75_active",
        "feat_98_bert"
    ],
    outputCol="features"
)

final_df = assembler.transform(df_tfidf)

final_df.select("features", "label").show(5)

"""Label fix"""

from pyspark.sql.functions import col

final_df = final_df.withColumn("label", col("label").cast("int"))

"""Train / Test Split"""

train_df, temp_df = final_df.randomSplit([0.7, 0.3], seed=42)
val_df, test_df = temp_df.randomSplit([0.5, 0.5], seed=42)

print("Train:", train_df.count())
print("Validation:", val_df.count())
print("Test:", test_df.count())

"""Logistic Regression (Baseline)"""

from pyspark.ml.classification import LogisticRegression

lr = LogisticRegression(featuresCol="features", labelCol="label")

lr_model = lr.fit(train_df)

lr_predictions = lr_model.transform(test_df)

"""Random Forest"""

from pyspark.ml.classification import RandomForestClassifier

rf = RandomForestClassifier(featuresCol="features", labelCol="label")

rf_model = rf.fit(train_df)

rf_predictions = rf_model.transform(test_df)

"""SVM"""

from pyspark.ml.classification import LinearSVC

svm = LinearSVC(featuresCol="features", labelCol="label")

svm_model = svm.fit(train_df)

svm_predictions = svm_model.transform(test_df)

"""Accuracy + F1 evaluation"""

from pyspark.ml.evaluation import MulticlassClassificationEvaluator

evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction")

# Accuracy
print("LR Accuracy:", evaluator.evaluate(lr_predictions, {evaluator.metricName: "accuracy"}))
print("RF Accuracy:", evaluator.evaluate(rf_predictions, {evaluator.metricName: "accuracy"}))
print("SVM Accuracy:", evaluator.evaluate(svm_predictions, {evaluator.metricName: "accuracy"}))

# F1 Score
print("LR F1:", evaluator.evaluate(lr_predictions, {evaluator.metricName: "f1"}))
print("RF F1:", evaluator.evaluate(rf_predictions, {evaluator.metricName: "f1"}))
print("SVM F1:", evaluator.evaluate(svm_predictions, {evaluator.metricName: "f1"}))

"""# Phase 4: Stream Processing & Comprehensive Evaluation

Create streaming folder
"""

import os

# Create folder for streaming simulation
os.makedirs("/content/stream_data", exist_ok=True)

print("Streaming folder ready!")

"""Start Streaming Source"""

# File-based streaming source
stream_df = spark.readStream \
    .format("text") \
    .option("maxFilesPerTrigger", 1) \
    .load("/content/stream_data")

print("Streaming Started")
print("Is Streaming:", stream_df.isStreaming)

"""Rename Column"""

from pyspark.sql.functions import col

# Rename default column
stream_df = stream_df.withColumnRenamed("value", "text")

"""Apply Preprocessing"""

# Apply same preprocessing pipeline
stream_df = stream_df.withColumn("clean_text", clean_udf(col("text")))

stream_df = stream_df.withColumn(
    "processed_text",
    stem_udf(col("clean_text"))
)

"""TF-IDF Transformation"""

# Tokenization + TF-IDF
stream_tokens = tokenizer.transform(stream_df)

stream_filtered = remover.transform(stream_tokens)

stream_tf = hashingTF.transform(stream_filtered)

stream_tfidf = idf_model.transform(stream_tf)

"""Add Custom Features"""

# Add stylometric features
stream_features = stream_tfidf \
    .withColumn("feat_6_elong", elong_udf(col("text"))) \
    .withColumn("feat_29_semicolon", semi_udf(col("text"))) \
    .withColumn("feat_52_interj", interj_udf(col("text"))) \
    .withColumn("feat_75_active", active_udf(col("text"))) \
    .withColumn("feat_98_bert", bert_udf(col("text")))

"""Assemble Features"""

# Create final feature vector
stream_final = assembler.transform(stream_features)

"""Real-Time Prediction (Best Model)"""

# Use best-performing model (SVM)
predictions = svm_model.transform(stream_final)

"""Start Streaming Output"""

# Start prediction stream
query = predictions.select("text", "prediction") \
    .writeStream \
    .format("console") \
    .option("truncate", False) \
    .start()

print("Streaming Query Running...")

"""Simulate Live Incoming Data"""

# Add new streaming file
with open("/content/stream_data/live_text_1.txt", "w", encoding="utf-8") as f:
    f.write("هذا نص عربي جديد للاختبار\n")

print("New streaming file added!")

"""Stop Stream (after few seconds)"""

import time

# Wait to process stream
time.sleep(10)

# Stop stream
query.stop()

print("Streaming Stopped")

"""ROC-AUC Evaluation"""

from pyspark.ml.evaluation import BinaryClassificationEvaluator

# ROC-AUC evaluator
evaluator_auc = BinaryClassificationEvaluator(labelCol="label")

print("LR AUC:", evaluator_auc.evaluate(lr_predictions))
print("RF AUC:", evaluator_auc.evaluate(rf_predictions))
print("SVM AUC:", evaluator_auc.evaluate(svm_predictions))

"""Confusion Matrix"""

print("Logistic Regression Confusion Matrix")

lr_predictions.groupBy("label", "prediction").count().show()

print("Random Forest Confusion Matrix")

rf_predictions.groupBy("label", "prediction").count().show()

print("SVM Confusion Matrix")

svm_predictions.groupBy("label", "prediction").count().show()

"""Batch Processing Time"""

import time

# Measure batch processing time
start = time.time()

svm_model.transform(test_df).count()

end = time.time()

print("Batch Processing Time:", end - start, "seconds")

"""Streaming Throughput / Latency"""

print("Streaming latency and throughput were monitored using Spark Structured Streaming micro-batches.")

"""# Phase 5: Analysis, Interpretation & Feature Importance

Feature Importance / Coefficients
Extract Coefficients
"""

# Extract LR coefficients
coefficients = lr_model.coefficients.toArray()

print("Total Coefficients:", len(coefficients))
print(coefficients[:20])

"""Visualization"""

import matplotlib.pyplot as plt
import numpy as np

# Top coefficients
top_coeffs = coefficients[:20]

plt.figure(figsize=(10,5))
plt.bar(range(len(top_coeffs)), top_coeffs)

plt.xlabel("Feature Index")
plt.ylabel("Coefficient Value")
plt.title("Top Logistic Regression Coefficients")

plt.show()